config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe

  get '/shopping_list', to: 'shopping_list#index'

  resources :users do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id'
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :find_user

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = @user
    if @recipe.save
      redirect_to recipe_path(id: @recipe.id), notice: 'Recipe created successfully'
    else
      flash.now[:alert] = @recipe.errors.full_messages.first if @recipe.errors.any?
      render :new, status: 400
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
    @recipe_foods.each(&:destroy)
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was deleted successfully'
    else
      flash.now[:alert] = @recipe.errors.full_messages.first if @recipe.errors.any?
      render :index, status: 400
    end
  end

  def toggle
    @recipe = Recipe.find(params[:id])
    @recipe.public = !@recipe.public
    text = @recipe.public? ? 'public' : 'private'

    if @recipe.save
      flash[:notice] = "#{@recipe.name} is now #{text}!"
    elsif @recipe.errors.any?
      flash[:alert] = @recipe.errors.full_messages.first
    end
    redirect_to recipe_path(id: @recipe.id)
  end

  private

  def find_user
    @user = current_user
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="recipes-container">
  <% @recipes.each do |recipe| %>
  <div class="recipe-card">
    <div class="recipe-title">
      <h3 class="recipe_name"><%= link_to recipe.name, recipe_path(id: recipe.id) %></h3>
      <% if can? :destroy, recipe %>
        <%= button_to "Remove", recipe_path(id: recipe.id), data: { turbo_method: :delete }, method: :delete, "turbo-frame": "recipes" %>
      <% end %>
    </div>
    <div class="recipe-features">
      <p class="recipe_desc"><%= recipe.description%></p>
    </div>
  </div>
  <% end %>


  <div class="add-recipe">
    <button class="recipe-btn"><%= link_to "Add Recipe", new_recipe_path %></button>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="back-button">
  <button type="button"><%= link_to "Back to recipes", recipes_path %></button>
</div>

<div class="new-recipe-container">
<h2 class="title">New Recipe</h2>
<div class="new-recipe">
  <%= form_with model: @recipe, url: recipes_path, local: true do |f| %>
    <div>
      <%= f.label :name, 'Recipe name'%><br>
      <%= f.text_field :name,class: "form-control"%>
    </div>
    <div>
      <%= f.label :description, 'Description'%><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div>
      <%= f.label :preparation_time, 'Preparation Time'%><br>
      <%= f.number_field :preparation_time, class: "form-control" %>
    </div>
    <div>
      <%= f.label :cooking_time, 'Cooking Time'%><br>
      <%= f.number_field :cooking_time, step: 0.5, class: "form-control" %>
    </div>
    <div>
      <%= f.label :public, "Do you want to make it public?", class: "public" %>
      <%= f.check_box :public%><br/>
    </div>
    <div class="submit">
      <%= f.submit "Create Recipe", class: "food-create" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="recipe-details-container">
  <h1 class="title"><%= @recipe.name %></h1>

  <div class="recipe-details">
    <div class="all-details">
      <p class="detail"><span><strong>Preparation Time: </span></strong><span><%= @recipe.preparation_time %> minutes</span></p>
      <p class="detail"><span><strong>Cooking Time:</span></strong> <span><%= @recipe.cooking_time %> minutes</span></p>
      <p class="detail"><%= @recipe.description %></p>
    </div>
    <% if (@recipe.user == current_user) %>
      <div class="toggle">
        <div class="private"><%=@recipe.public? ? 'Public' : 'Private'%></div>
        <%= button_to @recipe.public? ? 'Make private' : 'Make public', toggle_recipe_path(id: @recipe.id), method: :post, class: 'toggle_btn', remote: true %> 
      </div>
    <% end %>
  </div>

  <div class="buttons">
    <button><%= link_to "Generate shopping list", shopping_list_path%></button>
    <button class="recipe_btn"><%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe.id) %></button>
  </div>

  <% if @recipe.public? || (@recipe.user == current_user) %>
    <div class="recipes-container">
      <table class="table recipe-table">
        <thead>
          <tr>
            <th class="list_food name title">Food</th>
            <th class="list_food title">Quantity</th>
            <th class="list_food title">Value</th>
            <th class="list_food title">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_foods.each do |recipe_food| %>
            <tr class="food">
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %></td>
              <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
              <td class="modify-remove">
                <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-primary" %>
                <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, data: { confirm: "Are you sure you want to delete this recipe food?" }, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>