config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe

  get '/shopping_list', to: 'shopping_list#index'

  resources :users do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  root "recipes#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   <%= link_to 'Public recipes', public_recipes_path,  class: 'navbar-brand' %> 
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="btn-group">
            <%= link_to 'My recipes', recipes_path,  class: 'btn btn-outline-primary' %> 
            <%= link_to 'My foods', foods_path,  class: 'btn btn-outline-primary' %> 
            <%= link_to 'Create new recipe', new_recipe_path,  class: 'btn btn-outline-primary' %> 
            <%= link_to 'Public recipes', public_recipes_path,  class: 'btn btn-outline-primary' %>
            <%= link_to "Shopping list", shopping_list_path, class: 'btn btn-outline-primary' %>
            <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger' %> 
          </li>
        <%else%>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path,  class: 'btn btn-outline-primary' %> 
          <%= link_to 'Sign in', new_user_session_path,  class: 'btn btn-outline-primary' %> 
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>