config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe

  get '/shopping_list', to: 'shopping_list#index'

  resources :users do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :delete_all
  # belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :user, class_name: 'User'

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { only_float: true, greater_than_or_equal_to: 0 }
  validates :quantity, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods.order(created_at: :desc)
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
      else
        format.html { render :new, alert: 'Food could not be created' }
      end
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])
    if @food.destroy
      redirect_to foods_path, notice: 'Food was deleted successfully'
    else
      flash.now[:alert] = @food.errors.full_messages.first if @food.errors.any?
      render :index, status: 400
    end
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<div>
  <div class="new-food">
  <%= form_with url: foods_path, scope: :food do |form| %>
    <div >
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.label :Name %><br>
    <%= form.text_field :name, class: "form-control", require: true %>
    </div>
    <div>
    <%= form.label :Measurement_Unit %><br>
    <%= form.text_field :measurement_unit, class: "form-control", require: true %>
    </div>
    <div>
    <%= form.label :Price %><br>
    <%= form.number_field :price, class: "form-control", require: true %>
    </div>
    <div>
    <%= form.label :Quantity %><br>
    <%= form.number_field :quantity, class: "form-control", require: true %>
    </div>
    <div class="submit">
    <%= form.submit "Create Food", class: "food-create" %>
    </div>
  <% end %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="container">
  <h2 class="title">Foods list</h2>
  
  <table class="table table-bordered table-hover">
    <thead class="table-secondary">
      <tr>
        <th>Food</th>
        <th>Measurement unit</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
  
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <th class="align-middle"><%= food.name %></th>
          <td class="align-middle"><%= food.measurement_unit %></td>
          <td class="align-middle">$<%= food.price %></td>
          <td class="align-middle"><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'Add Food', new_food_path, class: "btn btn-success"%>
</div>

app/views/foods/new.html.erb
<div  class="container">
  <div class="text-center">
		<h1>Add new food</h1>
	</div>
		<%= render 'form', food: @food %>
		<div class="text-center">
		<%= link_to 'Back', url_for(:back) %>
		</div>
	</div>
</div>