config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :public_recipes, only: [:index]
  
  post 'recipes/:id/toggle', to: 'recipes#toggle', as: :toggle_recipe

  get '/shopping_list', to: 'shopping_list#index'

  resources :users do
    resources :foods, only: [:index, :show, :new, :create, :destroy]
  end
  # Defines the root path route ("/")
  root "recipes#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_recipe
  before_action :authorize_recipe_access

  def index
    @recipe_food = RecipeFood.new
    @recipe_id = params[:recipe_id]
  end

  def show
    @recipe_food = @recipe.recipe_foods
  end

  def new
    @foods = current_user.foods.all
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find_by_id(params[:id])
    @recipe_food.quantity = recipe_food_params[:quantity]
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe Food was updated successfully'
    else
      flash.now[:alert] = @recipe_food.errors.full_messages.first if @recipe_food.errors.any?
      render :edit, status: 400
    end
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe = @recipe
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe Food created successfully'
    else
      flash.now[:alert] = @recipe_food.errors.full_messages.first if @recipe_food.errors.any?
      render :new, status: 400
    end
  end

  def destroy
    if can? :edit, @recipe
      @recipe_food = RecipeFood.find(params[:id])
      if @recipe_food.destroy
        redirect_to recipe_path(@recipe), notice: 'Recipe Food was deleted successfully'
      else
        flash.now[:alert] = @recipe_food.errors.full_messages.first if @recipe_food.errors.any?
        render :new, status: 400
      end
    else
      flash[:alert] = 'ized'
      redirect_to recipe_path(id: @recipe.id)
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find_by_id(params[:recipe_id])
  end

  def authorize_recipe_access
    return unless @recipe.present? && current_user != @recipe.user

    flash[:alert] = 'You are not authorized to modify this recipe'
    redirect_to recipe_path(id: @recipe.id)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<h2 class="title">Edit Recipe Food Quantity</h2>

<div class="recipes-container">
  <h4>Current quantity value: <%= @recipe_food.quantity %></h4>
<%= form_with scope: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food), method: :patch, local: true do |f| %>
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 0 %>
    <% if @recipe_food.errors[:quantity].any? %>
      <div class="invalid-feedback">
    <%= @recipe_food.errors[:quantity].join(', ') %>
      </div>
    <% end %>
    <%= f.submit "Update", class: "btn btn-primary" %>
    <%= link_to "Cancel", recipe_path(@recipe), class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<%= link_to 'Back to recipe', recipe_path(@recipe), class:"btn btn-primary back-recipe" %>
<h2 class='title'> Add food to Recipe</h2>
<div class="recipe-food-new">
  <%= form_with url: recipe_recipe_foods_path, scope: :recipe_food do |form| %>
    <div>
      <%= form.label :food, class:"form-label" %><br>
      <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-control" %><br>
    </div>

    <div>
      <%= form.label :quantity, class:"form-label" %><br>
      <%= form.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
    </div>

    <div class="recipe-food-btns">
      <%= form.submit "Add", class:'recipe-create'%>
    </div>
  <%end%>
</div>